RecycleCoinProject/Controllers/SendigRcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntityLayer.Concrete;
using DataAccessLayer.Abstract;
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using DataAccessLayer.Concrete;

namespace RecycleCoinProject.Controllers
{
    public class SendigRcController : Controller
    {
        // GET: SendigRc
        UserInfoMenager um = new UserInfoMenager(new EfUserInfoDal());
        UserProductMenager UserProductMenager = new UserProductMenager(new EfUserProductDal());
        WalletMenager walletMenager = new WalletMenager(new EfWalletDal());
        Context c = new Context();

        
        [HttpGet]
        [Authorize(Roles = "A")]
        public ActionResult Index(int id=0)
        {
            string p = (string)Session["Email"];
            TempData["var"] = p;

            UserProduct userProduct = new UserProduct();

            id = c.Logins.Where(x => x.Email == p).Select(y =>
             y.UserID).FirstOrDefault();
            var deger = um.GetById(id);
            var rcvalue  = c.Wallets.Where(x => x.UserID == id).Select(y =>
             y.RcBalance).FirstOrDefault();
            int productcount = c.userProducts.Count(e => e.UserID == id && e.ProductStatus == true);
            TempData["balance"] = deger.Balance;
            TempData["count"] = productcount;
            TempData["rcvalue"] = rcvalue;
            um.GetUserInfoList();


            return View();



        }
        [HttpPost]
        public ActionResult Index(string rcinput)
        {
          
            string mailinfo = (string)Session["Email"];
            var id = c.Logins.Where(x => x.Email == mailinfo).Select(y =>
         y.UserID).FirstOrDefault();
            double s1 = Convert.ToDouble(rcinput);
            
            var deger = walletMenager.GetById(id);
            
            Wallet wallet = new Wallet();
            deger.RcBalance -= s1;
       
          
           

          
            walletMenager.WalletUpdate(deger);
         


            ViewBag.p = id;
            ViewBag.a = id;
            return RedirectToAction("Index");

        }


    }
}

RecycleCoinProject/Views/SendigRc/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}




<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper" style="color:darkblue"> 
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 style="color:#3e0563">Send RC COİN</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Wallet</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid ">
            <div class="row justify-content-md-center">
                <div class="col-12 ">

                </div>

                <div class="col-md-6">
                    <!-- Widget: user widget style 1 -->
                    <div class="card card-widget widget-user">
                       
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="widget-user-header bg-dark">
                            <p>sdmsdljkj</p>
                            <h3 class="widget-user-username">@TempData["var"]</h3>
                        </div>

                        <div class="card-footer">
                            <div class="row  justify-content-md-center">
                                <div class="col-sm-4 border-right">
                                    <div class="description-block">
                                        <h5 class="description-header">@TempData["balance"]</h5>
                                        <span class="text-black-50">The carbon you have</span>
                                    </div>
                                    <!-- /.description-block -->
                                </div>
                                <!-- /.col -->
                                <div class="col-sm-4 border-right">
                                    <div class="description-block">
                                        <h5 class="description-header">@TempData["rcvalue"]</h5>
                                        <span class="text-black-50"><a>The Recycle Coin you have</a></span>
                                    </div>
                                    <!-- /.description-block -->
                                </div>
                                <!-- /.col -->
                                <div class="col-sm-4">
                                    <div class="description-block">
                                        <h5 class="description-header">@TempData["count"]</h5>
                                        <span class="description-text">PRODUCTS</span>
                                    </div>
                                    <!-- /.description-block -->
                                </div>

                                <div class="col-12" style="text-align: center;">
                                    <b> 0403efcdac38e6e4aa3d06d57184f1df245998f7e7761baf9a0236e5a54ca5379cfd937c0</b>
                                    <br>
                                    <p>SHA 256 ADRESİ</p>
                                </div>

                                @using (Html.BeginForm("Index", "SendigRc", FormMethod.Post))
                                {
                                    <form class="col-8">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">How many coins do you want to send</label>
                                            <input type="text" class="form-control" name="rcinput" id="exampleInputEmail1" placeholder="Enter rc coin ">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Receiving address</label>
                                        
                                            <input type="text" class="form-control" name="Sha256" id="exampleInputPassword1" placeholder="Enter Sha-256" >
                                        </div>

                                        <div class="col-md-12">
                                            <div class="card card-primary collapsed-card">
                                                <div class="card-header">
                                                    <div class="form-check">
                                                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                                        <label class="form-check-label" for="exampleCheck1">Okudum onaylıyorum</label>
                                                    </div>

                                                    <div class="card-tools">
                                                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                                            <i class="fas fa-plus"></i>
                                                        </button>
                                                    </div>

                                                    <!-- /.card-tools -->
                                                </div>
                                                <!-- /.card-header -->
                                                <div class="card-body">
                                                    Yukarıda bulunan SHA 256 adresi bana aittir carbonların rc dönüşümünü kabul ediyorum
                                                </div>
                                                <!-- /.card-body -->
                                            </div>
                                            <!-- /.card -->
                                        </div>


                                        <button type="submit" class="btn btn-block btn-primary btn-lg">Recycle Coin Gönder</button>

                                    </form>
                                    <!-- /.col -->
                                }
                            </div>

                            <!-- /.row -->
                        </div>
                    </div>
                    <!-- /.widget-user -->
                </div>


            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->